### PR TITLE
Updates for SDK 3.0.0

### PR DESCRIPTION
**Pull request by abehaskins**

### CODE REVIEW

**Comment by cmosguy** [comment]
@abehaskins @Resonantjacket5 I just did some major edits in this PR: https://github.com/firebase/firechat/pull/61  I am not sure what is going to happen, but there were quite a few changes that needed updating to work with the latest account/console in Firebase, also including the new SDK release.  @firebase-ops You may want to look into this.

**Comment by jwngr** [comment]
@abehaskins - Ping on this PR. There seem to be lots of people asking about this on GitHub and the Google Group. Would be awesome to get this upgraded 🏭

**Comment by abehaskins** [comment]
Thanks for the ping! I thought this had gotten pushed out, will take a look this week :)

**Comment by cmosguy** [comment]
I pretty much fixed it all for you in the PR

**Comment by jwngr** [comment]
Thanks for doing that @cmosguy! Abe will take a look at your branch and get it merged in as soon as he has some time.

**Comment by jwngr** [comment]
Okay, I'll take this over and get it done. This PR (and #61) both still need a fair amount of work to get all the examples working and making sure the code is correct. I've started on that with a new branch [here](https://github.com/firebase/firechat/tree/pr/61). Hopefully will get this updated by the end of next weekend.

Thanks for your patience.

**Comment by jwngr** [comment]
Closing in favor of #66.

**Pull request closed without merging**
