### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by eliuha**
<div> element in header was not closed

### CODE REVIEW

**Comment by eliuha** [comment]
I signed it!

**Comment by vochicong** [comment]
No merge or reject for 8 months? 
Have your guys at Firebase stopped working on this project?

**Comment by markus8585** [comment]
This is indeed sad. 😞

**Comment by abehaskins** [comment]
Hey guys,

Sorry for the delay - to officially confirm, this project is in stasis. It does not have any dedicated engineering efforts assigned to it so it's very hard to even get simple PRs reviewed. 

This is an obvious change, so I'll accept it, I'm sorry about the delay - I know how frustrating it is to get no response when you're just trying to help.

All the best,
abe

**Pull request merged**
