### PR TITLE
Fix error in function definition.

### PR DESCRIPTION
**Pull request by avinoamm**

### CODE REVIEW

**Comment by avinoamm** [comment]
I signed it!
also I am Google employee

**Comment by cmosguy** [comment]
Hi @avinoamm @abehaskins,

It looks like there is some error int he function for .child in v3.0.0?

```javascript
this._messageRef     = this._firebase.child('room-messages');
```
I get the error:

```
firechat.js:125 Uncaught TypeError: this._firebase.child is not a function
```

Not sure what to do here.  Any advice?

I am going down this rat hole because Firebase is claiming I did not enable Twitter authentication.  However, I know I did, so I tried upgrading to v3.0.0 of the SDK .  This is how I am here for the firechat stuff.

Cheers!

**Comment by avinoamm** [comment]
cmosguy@ this change should fix that error:

https://github.com/firebase/firechat/pull/58/files/e1dd28e9b29445ae3c7d67dbeadce5bfa23224c4..45b6d90c51066375a805fde735132bff8a84d021

**Comment by cmosguy** [comment]
@avinoamm thank you for your response, however, fixing that line does not help.  Did they remove .child() function from the Firebase SDK?  because it is not working.  I am referrring to version 3.0.3 of the SDK.

**Comment by cmosguy** [comment]
k

**Comment by avinoamm** [comment]
They didn;t remove child().
cmosguy@ try the new commit maybe it will work.

**Comment by cmosguy** [comment]
Not sure what you mean by new commit? You have to use my updates or thinks
will not be irk at all.

**Comment by jwngr** [comment]
Closing in favor of #66. Thanks for the contribution and sorry we won't be using this branch!

**Pull request closed without merging**
